### ISSUE TITLE
Using roles for users and adding banners with profile pictures

### ISSUE THREAD

**Issue by SSP6904** [cornflourblue/next-js-13-mysql-registration-login-example#2]
Hi guys!

I'm wondering if I can make roles for a user that is a administrator for editing and deleting users instead of anyone able to do that.

Also able to add a banner and profile picture section.

Thank you!

**Comment by LostName1** [comment]
I was also looking to lock the users section for admin users only but I couldnt make it work, did you manage to create that functionality?

**Comment by SSP6904** [comment]
Nope. I haven't really paid attention to this repo for a while, but I have to look up that type of function to work on Next.js.

**Comment by LostName1** [comment]
> Nope. I haven't really paid attention to this repo for a while, but I have to look up that type of function to work on Next.js.

Same here, I need to make that feature work, the problem is I can't even make querys to the DB, did you even manage to make that?
